# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TaskManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'iOSDropDown'
  pod 'IQKeyboardManager'
  pod 'FSCalendar'
  pod 'SVProgressHUD'
  pod 'Google-Mobile-Ads-SDK'
  # Pods for TaskManager

end
